.TH ILS 1 
.ad
.fi
.SH NAME
ils
\-
list inode information
.SH SYNOPSIS
.na
.nf
.ad
.fi
\fBils\fR [\fB-eorvV\fR] [\fB-f \fIfstype\fR]
\fIdevice\fR [\fIstart-stop\fR ...]

\fBils\fR [\fB-aAlLvVzZ\fR] [\fB-f \fIfstype\fR]
\fIdevice\fR [\fIstart-stop\fR ...]
.SH DESCRIPTION
.ad
.fi
\fBils\fR opens the named \fIdevice\fR and lists inode information.
By default, \fBils\fR lists only the inodes of removed files.

Arguments:
.IP \fB-e\fR
List every inode in the file system.
.IP "\fB-f\fI fstype\fR"
Specifies the file system type. The default file system type
is system dependent. With most UNIX systems the default type
is \fBffs\fR (Berkeley fast file system). With Linux the default
type is \fBext2fs\fR (second extended file system).
.IP \fB-o\fR
List only inodes of removed files that are still open or executing.
This option is short-hand notation for \fB-aL\fR
(see the \fBfine controls\fR section below).
.IP \fB-r\fR
List only inodes of removed files. This option is short-hand notation
for \fB-LZ\fR
(see the \fBfine controls\fR section below).
.IP \fB-v\fR
Turn on verbose mode, output to stderr.
.IP \fB-V\fR
Turn on verbose mode, output to stdout.
.IP \fIdevice\fR
Disk special file, or regular file containing a disk image.
On UNIX systems, raw mode disk access may give better performance
than block mode disk access.  LINUX disk device drivers support
only block mode disk access.
.IP "\fIstart-stop\fR ..."
Examine the specified inode number or number range. Either the
\fIstart\fR, the \fIstop\fR, or the \fI-stop\fR may be omitted.
.PP
Fine controls:
.IP \fB-a\fR
List only allocated inodes: these belong to files with at least one
directory entry in the file system, and to removed files that
are still open or executing.
.IP \fB-A\fR
List only unallocated inodes: these belong to files that no longer
exist.
.IP \fB-l\fR
List only inodes with at least one hard link. These belong to files
with at least one directory entry in the file system.
.IP \fB-L\fR
List only inodes without any hard links. These belong to files that no
longer exist, and to removed files that are still open or executing.
.IP \fB-z\fR
List only inodes with zero status change time. Presumably, these
inodes were never used.
.IP \fB-Z\fR
List only inodes with non-zero status change time. Presumably, these
belong to files that still exist, or that existed in the past.
.PP
The output format is in time machine format, as described in
tm-format(5). The output begins with a two-line header that
describes the data origin, and is followed by a one-line header
that lists the names of the data attributes that make up the
remainder of the output:
.IP \fBst_ino\fR
The inode number.
.IP \fBst_alloc\fR
Allocation status: `a' for allocated inode, `f' for free inode.
.IP \fBst_uid\fR
Owner user ID.
.IP \fBst_gid\fR
Owner group ID.
.IP \fBst_mtime\fR
UNIX time (seconds) of last file modification.
.IP \fBst_atime\fR
UNIX time (seconds) of last file access.
.IP \fBst_ctime\fR
UNIX time (seconds) of last inode status change.
.IP \fBst_dtime\fR
UNIX time (seconds) of file deletion (LINUX only).
.IP \fBst_mode\fR
File type and permissions (octal).
.IP \fBst_nlink\fR
Number of hard links.
.IP \fBst_size\fR
File size in bytes.
.IP \fBst_block0,st_block1\fR
The first two entries in the direct block address list.
.SH SEE ALSO
.na
.nf
mactime(1), mtime, atime, ctime reporter
tm-format(5), time machine data format
.SH BUGS
.ad
.fi
\fBils\fR should support more file system types. Right now, support
is limited to \fBext2fs\fR when built on Linux, and \fBffs\fR when
built on Solaris and BSD systems.
.SH LICENSE
.na
.nf
This software is distributed under the IBM Public License.
.SH AUTHOR(S)
.na
.nf
Wietse Venema
IBM T.J. Watson Research
P.O. Box 704
Yorktown Heights, NY 10598, USA
